### ISSUE TITLE
可以添加类似于FabricProxy的allowBypassProxy功能吗

### ISSUE THREAD

**Issue by XiaoHuiHui233** [OKTW-Network/FabricProxy-Lite#14]
一些基于pyCraft的外部bot会因为直连服务器而不能进入，如果通过velocity进入服务器则无法绕过正版验证。
在FabricProxy有解决方案，就是使用allowBypassProxy配置项，这样就允许不通过modern forwarding的方式进入服务器。
能否考虑在Lite上适配Velocity并添加这个功能？

**Comment by james58899** [comment]
目前沒有計畫在Lite加入這個功能，繼續用FabricProxy就好了

**Comment by XiaoHuiHui233** [comment]
我是在Velocity上遇到这个问题的，FabricProxy目前还不支持Velocity吧？如果FabricProxy-Lite不支持，我想在Velocity上应该是没有其它解决方案了，而换回BC或者Waterfall是一个更加复杂的问题，因为与其它模组也有致命的兼容性问题（这也是最终选择Velocity的原因）。

**Comment by james58899** [comment]
modern forwarding就是Velocity的功能，也就是說FabricProxy支援Velocity

**Comment by XiaoHuiHui233** [comment]
好的 了解了 Velocity和FabricProxy都推荐使用FabricProxy-Lite 这让我以为它俩之间存在什么兼容性问题。
非常感谢
