### ISSUE TITLE
Not compatible with Origins mod

### ISSUE THREAD

**Issue by Epresin** [OKTW-Network/FabricProxy-Lite#18]
I installed Origins mod(https://www.curseforge.com/minecraft/mc-mods/origins)on the server and my client. And when connecting to this server through velocity, It shows 
'This server requires you to install the Origins mod (v1.3.1) to play.'
I tried turning off the ’performVersionCheck‘ option in the Origins config file. When I try to connect again, velocity shows 
'[17:07:11 ERROR]: [server connection] Epresin -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@33f555a6
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.'
After the client and server removed the origins mod, I was able to join the server.

[velocity latest.log](https://github.com/OKTW-Network/FabricProxy-Lite/files/8192253/latest.log)
[server latest.log](https://github.com/OKTW-Network/FabricProxy-Lite/files/8192257/latest.log)

**Comment by Epresin** [comment]
I also have this problem when using FabricProxy

**Comment by james58899** [comment]
Have you tried without FabricProxy-Lite?

**Comment by Epresin** [comment]
> 你有没有试过没有FabricProxy-Lite？

I tried it and it can join the server normally

**Comment by james58899** [comment]
You need to install [CrossStitch](https://modrinth.com/mod/crossstitch).
As origins mod only send command to player with OP permission, issue will only cause on OP join server.
Please refer to the velocity documentation: https://velocitypowered.com/wiki/users/server-compatibility/

**Comment by Epresin** [comment]
> 您需要安装 [CrossStitch](https://modrinth.com/mod/crossstitch)。由于源模组仅向具有OP权限的玩家发送命令建议，因此问题仅在OP加入服务器上引起。请参阅速度文档：https://velocitypowered.com/wiki/users/server-compatibility/

Thank you for your help.
