### ISSUE TITLE
Velocity dont work 1.18.1

### ISSUE THREAD

**Issue by Psycnotics** [OKTW-Network/FabricProxy-Lite#19]
Hi!
I try to connect 3 Fabric 1.18.1 Server "all with the same Mods" togheter! No chance ! I try everythink. Fabticproxy-Light is install and crossstitch too.. no way !! I cant log in.. i need Really HELP !  i cant log over Velocity to the Server, get alway disconect after few seconds and and no LOG . Modern is enable and so on.. but nothing works..

**Comment by james58899** [comment]
Are you able to login without FabricProxy-Lite?
FabricProxy-Lite will not change mod support for proxy.

**Comment by james58899** [comment]
Closed due to insufficient information.
