### ISSUE TITLE
Incompatible with Ledger in gameversion 1.17.1

### ISSUE THREAD

**Issue by seb303** [OKTW-Network/FabricProxy-Lite#21]
I still have [this issue](https://github.com/OKTW-Network/FabricProxy-Lite/issues/13) with the latest 1.17.1 FabricProxy-Lite-1.1.5.jar and ledger-1.1.1.jar

Should this fix have been applied to the 1.17.1 builds, or was the fix only for 1.18.x?

**Comment by james58899** [comment]
You can use 1.1.6.

**Comment by seb303** [comment]
Will 1.1.6 work with game version 1.17.1?
On CurseForge it only states 1.18
