### ISSUE TITLE
1.8.9?

### ISSUE THREAD

**Issue by Xiaohuang257** [OKTW-Network/FabricProxy-Lite#23]
https://github.com/Legacy-Fabric

**Comment by james58899** [comment]
We only support latest Minecraft version, no plans to support/maintain older versions.
And Legacy Fabric is missing `ServerLoginNetworking` API it is required for this mod.

If anyone wants to port to an older version, I recommend fork [FabricProxy](https://github.com/OKTW-Network/FabricProxy).
