### ISSUE TITLE
didn't support Origins-1.18.2-1.4.1

### ISSUE THREAD

**Issue by ghost** [OKTW-Network/FabricProxy-Lite#24]
If you use Origins-1.18.2-1.4.1 join velocity
Server will tell you:"You not install Origins-1.18.2-1.4.1 in you game"

**Comment by RealFX-Code** [comment]
Make sure to disable update checking in your origins config file!
E.G. set **performVersionCheck** to **False** in **config/origins_server.toml**

**Comment by arazadaz** [comment]
That's great and all, but is there a proper fix that can be done for this?

**Comment by james58899** [comment]
Handling mod compatibility with proxy is not a goal of FabricProxy.
