### ISSUE TITLE
Unable to send chat messages => kick

### ISSUE THREAD

**Issue by Aurelien30000** [OKTW-Network/FabricProxy-Lite#29]
Due to 1.19.1, I'm unable to send chat message to the server. Client is always kick for the following reason:
``Received chat packet with missing or invalid signature.``

The server is running behind a Velocity proxy.

Thanks!

_Full logs: https://paste.domicraft.fr/matasipexa.sql_

**Comment by james58899** [comment]
Are you using anything on the proxy that modifies the chat packet?

Preventing anything from modifying chat messages is one of the important updates for 1.19.1.

**Comment by Aurelien30000** [comment]
No the proxy may only read messages.

**Comment by james58899** [comment]
Can't reproduce the issue, I can send messages normally.

Can you provide more info about proxy and client?

![](https://user-images.githubusercontent.com/5798637/181710848-d2de0281-5e70-484c-a872-fdcebb51a5e5.png)

**Comment by Aurelien30000** [comment]
``force-key-authentication`` is set to false on both proxy and server, I don't know if this may cause issues. 

The client is a default minecraft client.

_It's not likely an issue with your mod but with velocity and a _special_ config 🤷 _

**Comment by james58899** [comment]
If you don't care chat report system, try install [No Chat Reports](https://modrinth.com/mod/no-chat-reports).
