### ISSUE TITLE
1.19.2 Fabric?

### ISSUE THREAD

**Issue by DecDuck** [OKTW-Network/FabricProxy-Lite#32]
I tried the `FabricProxy-Lite-2.1.1.jar` off Modrinth, just to see if it works, and I get a bunch of errors about mixins. Since the jar says it only support 1.19 or something, I'm assuming that it's not a bug. So I'm wondering when/if there will be a version released for 1.19.2? I don't mind building it myself from the source code, but I can't see any gradle tasks to do that.

**Comment by james58899** [comment]
Have you tried version 2.3.0?

**Comment by DecDuck** [comment]
I compiled the jar from the project files, but when I tried loading it, the server spat out an error about not being able to load some classes, so I'm assuming I didn't compile it correctly

**Comment by james58899** [comment]
You can download version 2.3.0 from Modrinth.

**Comment by DecDuck** [comment]
Oh you can. I feel kinda stupid now. Thank anyways, it solved my problem.
