### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by LibreMindMC** [OKTW-Network/FabricProxy-Lite#37]
Is there an estimate on when FabricProxy-Lite will support 1.19.3?

**Comment by james58899** [comment]
Velocity is not ready for 1.19.3 with secure chat enable.
If you don't need secure chat, you can try #35 and turn off `hackMessageChain`.

**Comment by james58899** [comment]
Released v2.4.0 support 1.19.3 but no secure chat.
