### ISSUE TITLE
Unable to acccess any fabric servers on Velocity 3.2.0

### ISSUE THREAD

**Issue by spacewulf** [OKTW-Network/FabricProxy-Lite#42]
I keep getting an error about the backend servers being in online mode, despite everything configured properly
Here's the error I keep getting: https://hastebin.com/uwelaxepof.properties
Running 1.19.2 fabricproxy-lite and crosstitch with fabricapi. Nothing else.

**Comment by james58899** [comment]
@FunnyShadow The player's connection has entered the `PLAY` stage, but fabricproxy only works in the `LOGIN` stage. I think it should be caused by other reasons.

**Comment by james58899** [comment]
@FunnyShadow I tried only adding the QSL mod, setting the server to offline and turning off player info forwarding, but I still can't log in to the server.

You should report the issue to Quilt, because QSL is causing this issue.

**Comment by james58899** [comment]
Stale, if still have problems, please open another issue.
