### ISSUE TITLE
Add Support for Legacy Forwarding

### ISSUE THREAD

**Issue by xanderforrest** [OKTW-Network/FabricProxy-Lite#48]
If possible, supporting legacy forwarding would allow a large amount of Pixelmon Networks to include Fabric servers (specifically Cobblemon, an upcoming Pokemon Mod) on their network.

Every Pixelmon 1.16 network is using a fork of Velocity alongside an added client reset packet, providing support for modern Forge (1.13+). Modern Forge support has the one drawback of only supporting legacy forwarding. Having the option to support it with FabricProxy-Lite (not by default, and with appropriate warnings for users who might not be aware of the security issues) would be massively useful for these servers, and the modded community in general. 

A large amount of servers will be looking to support Cobblemon in the future alongside their Pixelmon servers. To my knowledge, if legacy forwarding was supported with this mod, you'd be able to run a network with every mod loader & Minecraft version supported with a central hub, which is pretty neat. 

More info about the work done for Forge 1.13+ Proxy support can be found here:
-https://github.com/Just-Chaldea/Forge-Client-Reset-Packet
-https://github.com/PaperMC/Velocity/pull/932
-https://github.com/MinecraftForge/MinecraftForge/pull/9313

**Comment by james58899** [comment]
https://github.com/OKTW-Network/FabricProxy#third-party-forks
