### ISSUE TITLE
1.18.2 server (cabrility modpack) running quilt, "Timed out"

### ISSUE THREAD

**Issue by swz-git** [OKTW-Network/FabricProxy-Lite#52]
I'm using FabricProxy-Lite v1.1.6 as its the latest one with 1.18 support

**Comment by james58899** [comment]
Have you tested whether you can connect without FabricProxy-Lite? Quilt has known issues with Velocity, this is not related to FabricProxy-Lite and must be fixed by Quilt.

https://github.com/QuiltMC/quilted-fabric-api/issues/46

**Comment by james58899** [comment]
Closing due to no response and looks like a quilt issue.
