### ISSUE TITLE
Incompatible with pitch black

### ISSUE THREAD

**Issue by arazadaz** [OKTW-Network/FabricProxy-Lite#53]
This is similar to the origins incompatibility. #24 

 the mod [pitch black](https://github.com/arazadaz/pitch-black/tree/fabric) does not work with the proxy. This mod must validate any user and confirm they have the correct version in order to join.
 
Asides from this, there's actually a lot of incompatibilities with a lot of mods. As much as I would like to use this for my server, it just doesn't seem practical. If any dev is interested, I can give my modpack to test for incompatible mods. I spent hours on this though, and I would have to gut my entire modpack just about for this proxy mod to work properly and let users connect.

**Comment by james58899** [comment]
FabricProxy does not provide any mod compatibility, please give feedback to the mod author instead of FabricProxy.
