### ISSUE TITLE
Please fix incompatibility with ViaFabric!

### ISSUE THREAD

**Issue by RealKomander** [OKTW-Network/FabricProxy-Lite#71]
The only mods downloaded are:
- fabric-api-0.91.2+1.20.2
- FabricProxy-Lite-2.7.0
- ViaBackwards-4.10.0-23w51b-SNAPSHOT
- ViaFabric-0.4.11+50-dev
- ViaVersion-4.10.0-23w51b-SNAPSHOT
On fabric 1.20.2, installed specifically for testing

Whenever I try joining from 1.20.1, I get this error:

`[19:28:12] [Server thread/INFO]: com.mojang.authlib.GameProfile@487fc80c[id=b18a2b65-0131-4c4f-926c-f81305475690,name=RealKomander,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcwMzAwMzI4Mjg4MCwKICAicHJvZmlsZUlkIiA6ICJiMThhMmI2NTAxMzE0YzRmOTI2Y2Y4MTMwNTQ3NTY5MCIsCiAgInByb2ZpbGVOYW1lIiA6ICJSZWFsS29tYW5kZXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWVhYzA0YzUxYjMyMDMxODliMTkxOTc5ZjMyZTg0NDJlZmQ4MzhhYWVlNDM4ZDZiNGU5NWJhYTYxOGFmYzNlYyIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0=, signature=GT+MZsmdtOJ6Gv8b9dXYyZotpodIbPxePjscSKSnWvJbvfBJEQpJk398mfQhjia1gnU4e6wdn7rVB3pwPpCeql32R+kpdKhSI08VFPhEb0gdgdeB20FbFtdSsTlnBkPGOtwomnytyMAaXn5BkPtBrHgmuXz2mvX5Bn34WlulescwNHdxqAn+qIxoxf2DgVT63LvFK3y3AUnSbwLQtgsU606Qla7Gx9cxNbLMao7tqp8MLEgmlAr8tDuxg1MXkjXkm47c8sxy2PsNgdZoeKvGxLsU0cxM8qP+1WqZDHRQhJyPnAqDbhERYm8RkxSbENSk14wmGKO9XcLiw7LzPJCyNy9BJRJyaFdq5E8/OloiBx0BotZDBuSFyBZY8K6/ebSGp3KL/bgSqkeTbSG7146KBODbHSVH2IdXFz+uFKjWXetAyTbgOqI3gLGE7uYTHoV5MKkdQghjLSJzUrRV9FU4MpQwUq4T98JJ/21h7IMj5O2BeRq/nsitcAzugP1r3eb+PPmkPXbo9XX1XvLjxO0mkkjCC+PG1Hx/3I0CVOdCLUnv8Ow/yf+n5BqtgTI4sKAAKj8vYOEtV5GJZIYkvIBGfI8e8GhmnXheKzlP5yt8XRYQCLMn/Apw94qEzLbYf34if/9WpejDm+qh3FDkx6AwWIP/bSzdMoOV4RQw/z6P0/0=]]}] lost connection: Disconnected
`

I don't know what exactly causes this issue, I am sending it to both ViaVersion and Fabric Proxy Lite. I've had enough of this sort of errors, this is not the first one.
Sorry if I already reported it to somewhere else - this whole thing is a complete mess, mojang broke everything in 1.20.2, I haven't managed to make a successfully running server with full compatibility since the very release of this stupid version.

**Comment by RealKomander** [comment]
https://github.com/ViaVersion/ViaFabric/issues/289

**Comment by RealKomander** [comment]
This is what, the 3rd gibberish looking issue? I'm terribly sorry if I have already reported it and forgot about it, I've reported more than 10 errors regarding several mods and I'm starting to go insane

**Comment by ifacify** [comment]
There are several issues in terms of cross version compatibility with velocity + fabric + viaversion recently. Luckily I have gone through the trouble of investigating and identifying them and I might as well document them somewhere appropriate (maybe here as it is the main place fabric + velocity users go).  

## Problems:
- viabackwards has problem translating 1.20.1- to 1.20.2+ (viaversion is totally fine)
- fabric-carpet mod changed their protocol (blame mojong) in mc1.20.2 release causing netty decoding error, you have to install carpet on both c/s to trigger this
- to be added

## Solutions:
- Working fix is proposed to upstream [here](https://github.com/orgs/FabricMC/discussions/3391#discussioncomment-7903870). or you might prefer prebuilt jar: [via_for_1.20.4.zip](https://github.com/OKTW-Network/FabricProxy-Lite/files/13723948/via_for_1.20.4.zip)

- Uninstall carpet mod on either client/server, or install [this](https://git.jerryxiao.cc/mc/velocity-carpet-fix/releases/download/artifacts/velocity-carpet-fix-0.1-SNAPSHOT-all.jar) on your velocity proxy

## Some thoughts
I always install viaversion and viabackwards on the velocity proxy as it is much easier in terms of maintenance and updates. It seems that Via* mainly targets bukkit servers and their devs absolutely does not care about fabric servers or the idea of installing Via* on the proxy. So by doing any of these you are pretty much in the unsupported and untested area, identifying errors and fixing bugs are required skills.

**Comment by james58899** [comment]
Closed Since this doesn't look like an issue with FabricProxy-Lite.

**Comment by Kichura** [comment]
`their devs absolutely does not care about fabric servers or the idea of installing Via* on the proxy` - This sounds more an insult towards via's entire team.

Velocity has been working for quite a while and has been primarily the main target when choosing a proxy software to pair other servers and while i *(for example)* am aware of fabric servers and try my efforts to help people out with them, Trying to get certain mods to work with ViaFabric such as Polymer has unfortunately at the moment not been going well when asking the devs about it therefore the "help wanted" label is there in case somebody can find solutions to them.
