### ISSUE TITLE
2.7.0  error with "fabric-networking-api-v1-3.0."

### ISSUE THREAD

**Issue by paj1s** [OKTW-Network/FabricProxy-Lite#72]
I downloaded the newest version because of problems with luck perms pre uuid or something preventing me from connecting but this version is preventing the server even from starting so i had to downgrade to 2.6.0 and remove luck perms. It sometimes told me in the console that the conflicting mod is create but after removing it, it was still happening. Im posting full log.

[2023-12-26-4.log](https://github.com/OKTW-Network/FabricProxy-Lite/files/13767600/2023-12-26-4.log)

**Comment by james58899** [comment]
2.7.0 only supports 1.20.2 and does not change compatibility with LuckPerms.

Have you followed the mod description and enabled `hackEarlySend`?

**Comment by paj1s** [comment]
Yeah right after i posted this... sorry. So it works and i can close this i guess.
