### ISSUE TITLE
Commands in command blocks not forwarded to proxy

### ISSUE THREAD

**Issue by MrRedRhino** [OKTW-Network/FabricProxy-Lite#8]
Proxy commands (like /server) in command blocks are not sent to the proxy. I don't think, that this is intended to work, but since there is no suggestion-section, I post it here. So basically what I would like to see, is being able to send players to other servers via velocity-proxy with command blocks, so you don't have to have an admin typing the command.

**Comment by james58899** [comment]
Velocity support BungeeCord plugin channel.
You can write a mod to send packet to proxy let it switch the server.

Check [fabric-networking-api-v1](https://github.com/FabricMC/fabric/blob/e369698318eb899183a821f9bb7c91c149c8ede3/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/api/networking/v1/ServerPlayNetworking.java), [BungeeCord wiki](https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/#bungeecord-subchannel-specification) and [Velocity Javadoc](https://jd.velocitypowered.com/1.1.0/com/velocitypowered/api/event/connection/PluginMessageEvent.html)

**Comment by MrRedRhino** [comment]
thanks! imma try lol
