### ISSUE TITLE
FabricProxy-Lite conflict with some mods

### ISSUE THREAD

**Issue by Frankwu0915** [OKTW-Network/FabricProxy-Lite#81]
version
minecraft 1.17.1
fabric api 0.46.1
fabric loader 0.15.9
Installer Version 1.0.0
carpet 1.4.57

crash with 
Carpet-AMS-Addition-mc  v2.36.0
carpet-tis-addition-mc v1.57.1
g4mespeed-mc v1.4.6
ivan-carpet-addition-mc v2.2.2
ledger v1.1.1
magiclib-all v0.7.382+17856bd-beta

log＆crash report
[latest.log](https://github.com/OKTW-Network/FabricProxy-Lite/files/14861841/latest.log)
[crash-2024-04-04_13.09.50-server.txt](https://github.com/OKTW-Network/FabricProxy-Lite/files/14861843/crash-2024-04-04_13.09.50-server.txt)

**Comment by LJYXG** [comment]
> 版本 minecraft 1.17.1 fabric api 0.46.1 fabric loader 0.15.9 安装程序版本 1.0.0 carpet 1.4.57
> 
> 与 Carpet-AMS-Addition-mc v2.36.0 carpet-tis-addition-mc v1.57.1​​ g4mespeed-mc v1.4.6 ivan-carpet-addition-mc v2.2.2 ledger v1.1.1 magiclib-all v0.7.382+17856bd-beta崩溃
> 
> 日志和崩溃报告 [latest.log ](https://github.com/OKTW-Network/FabricProxy-Lite/files/14861841/latest.log) [crash-2024-04-04_13.09.50-server.txt](https://github.com/OKTW-Network/FabricProxy-Lite/files/14861843/crash-2024-04-04_13.09.50-server.txt)

You can try to downgrade the Fabric API. I encountered a similar problem in 1.16.5. After referring to this [reply](https://github.com/OKTW-Network/FabricProxy-Lite/issues/13#issuecomment-971939412), I downgraded the Fabric API and the problem was solved.
