### ISSUE TITLE
Forwarding options

### ISSUE THREAD

**Issue by AceSardonyx** [OKTW-Network/FabricProxy-Lite#82]
I really enjoy having a multi compatible server and not having legacy forwarding support takes away lot of my server's features.
Must modern be the only forwarding type?
This is a feature request and also bump to the two requests about sourced secret config and directly connecting without proxy.

**Comment by james58899** [comment]
Allow direct connect has a PR #68, but I'm not sure about merging it.
No plan to support legacy forwarding.
