### ISSUE TITLE
Conflicts with "exposure" and "bookshelf" mods

### ISSUE THREAD

**Issue by xZx-X-xZx** [OKTW-Network/FabricProxy-Lite#86]
After removing these two mods, players will be able to access the server normally.

This is when the error occurs.
![535e2b7937f1912c22f431494de1b6c](https://github.com/OKTW-Network/FabricProxy-Lite/assets/54734776/c5db63b9-7959-4242-a915-64c8f8d0dad2)

**Comment by james58899** [comment]
This is not caused by FabricProxy-Lite, please report the issue to those two mods.
