### ISSUE TITLE
"Can't serialize unregistered packet" error when connecting to Fabric server with mod installed

### ISSUE THREAD

**Issue by ZnapGaming** [OKTW-Network/FabricProxy-Lite#91]
Hi we have issues with the FabricProxy-Lite Mod for our Network usage, please have a look below:

_Environment:_
Minecraft version: 1.19.4
Mod version: 2.5.0
Server software: Fabric + fabric-api
Client software: Fabric
Velocity version: latest 3.3.0-SNAPSHOT

_Steps to reproduce:_
Install the mod on the fabric server
Start the server and client.
Attempt to connect to the server from the client.

_Expected behavior:_
The client should be able to connect to the server without any issues.

_Actual behavior:_
The client throws an error "Unable to connect" and fails to connect to the server.

_Logs:_
Please find the relevant log output below:
[Error message: "Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet"]

_Additional information:_
We have tried different versions of all software used but still got the same error at the end with unregistered packets.
The mod is only needed server-side right?
Our velocity setup uses new forwarding.

We think its a issue with the velocity communication of packets, is this a known issue or do you might have some more info for us about that? 

Thanks Guys!
Greets

**Comment by james58899** [comment]
1.19.4 is no longer supported. If there are still problems with the new version, please open a new issue.
