### ISSUE TITLE
server behind proxy doesn't send custom resource pack

### ISSUE THREAD

**Issue by morodirule** [OKTW-Network/FabricProxy-Lite#96]
I am running 1.21 fabric server with mod polymer
got this error message when trying to connect
![image](https://github.com/user-attachments/assets/a759e82c-7ee0-42eb-b957-d632a81eff13)

**Comment by ArkoSammy12** [comment]
Having the same issue here 👍🏻

**Comment by james58899** [comment]
I don't think this is caused by this mod, have you tried removing fabricproxy?

**Comment by morodirule** [comment]
removing and re adding helped thx
