### ISSUE TITLE
v2.9.0 doesn't work with latest Fabric Server (1.21.3)

### ISSUE THREAD

**Issue by benno0dev** [OKTW-Network/FabricProxy-Lite#99]
The console says the mod needs Java 17, but the server needs at least Java 21

**Comment by james58899** [comment]
Minecraft 1.20.5 and above requires Java 21.

If you have any other issue please provide the full log.

**Comment by benno0dev** [comment]
i am using 1.21.3 with java 21.0.5
here is my full log:
https://pastebin.com/32t5acWF

**Comment by benno0dev** [comment]
No i fixed it now, the problem was the forge loader version that is installed with crafty
no fabric api is needed
